name: ci

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc
      - name: Install dependencies
        run: npm ci
      - name: Check
        run: npm run check
      - name: Build
        run: npm run build
      - name: Build examples
        run: npm run build:examples
      - name: Test
        run: npm run test:ci

  integration:
    needs: ci
    if: needs.ci.result == 'success' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:ci
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
      - name: Check vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Code analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
      - name: Upload code analysis results
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
      - name: License scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}

  release:
    needs: integration
    if: needs.integration.result == 'success' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install latest npm
        run: |
          npm install -g npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Prepare package
        run: |
          npm run prepublishOnly
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: './.github/configs/changelog.json'
          owner: carlocorradini
          repo: graphql-auth-directive
          failOnError: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
