name: ci

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    env:
      RUN_STEP: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.node-version == '16.x' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc
      - name: Install dependencies
        run: npm ci
      - name: Checks
        run: npm run check
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:coverage
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        if: ${{ env.RUN_STEP }}
      - name: Check vulnerabilities
        uses: snyk/actions/node@master
        if: ${{ env.RUN_STEP }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: License scan
        uses: fossas/fossa-action@main
        if: ${{ env.RUN_STEP }}
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
      - name: Code analysis
        uses: codacy/codacy-analysis-cli-action@master
        if: ${{ env.RUN_STEP }}
        with:
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
      - name: Upload code analysis results
        uses: github/codeql-action/upload-sarif@main
        if: ${{ env.RUN_STEP }}
        with:
          sarif_file: results.sarif

  release:
    needs: ci
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: graphql-auth-directive ${{ env.RELEASE_VERSION }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
