name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc
      - name: Install dependencies
        run: npm ci
      - name: Checks
        run: npm run check
      - name: Build
        run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: graphql-auth-directive ${{ env.RELEASE_VERSION }}
      - name: Publish package on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
